apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: istio-system
spec:
  hosts:
    - "*"
  gateways:
    - main-gateway
  http:
    # 1. / → /nginx'e redirect et
    - match:
        - uri:
            exact: /
      redirect:
        uri: /nginx

    # 2. /nginx → nginx servisine yönlendir ve URI'yi / yap (rewrite)
    - match:
        - uri:
            prefix: /nginx
      rewrite:
        uri: /
      route:
        - destination:
            host: nginx-service.default.svc.cluster.local
            port:
              number: 80
